### ISSUE TITLE
Detective work for missing logs between May 2017 and October 2017

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#148]
@clayadavis I have checked under `/l/cnets/research/BotOrNot/logs/` and indeed I have uploaded all those logs, so there were none extra that I found. 

In short, we are still missing those logs between May and October, let me know if you think there could be somewhere else and if not, we can stop looking into it.

**Comment by clayadavis** [comment]
This is the exactly the period that we were using rotating logs because we'd just filled up Carl's data disk with that enormous `botornot.log201705.gz`file that was, at the time, uncompressed. I guess something went wrong with the rotating logs; we weren't paying them a lot of attention at that time. It's my fault. While sad, it happens sometimes. Hopefully our solution is more robust moving forward.
