### ISSUE TITLE
There is a color discrepancy in the color scheme between Firefox and Chrome

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#198]
As seen below (left=Firefox, right=Chrome). Firefox tends to have a darker color scheme where Human-Likely nodes are more blue while the middle (hybrid colors) tend to be different between Firefox and Chrome.

![firefoxchromecolordiscrepancy](https://user-images.githubusercontent.com/24797255/35744534-9c916d5a-080e-11e8-9ee2-d988f5e0d54e.png)

**Comment by benabus** [comment]
I've checked this in chrome vs firefox on my machine and don't see a difference.  Making it 100% pixel perfect across browsers is virtually impossible regardless.  This is most likely caused by how the browsers render transparency in the versions/operating system/screens tested.  Based on my experience, trying to fix this sort of bug would likely take forever and I don't feel like the cost-benefit is worth it.

**Comment by benabus** [comment]
Closing as a non issue
