### ISSUE TITLE
In Hoaxy search move selected articles above the visualization and compress them

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#206]
Compress the article list and only show the selected one while having the option to view more and select more.  Include the article list in the frame of the visualization (or at least part of it). That way the user is aware what he or she is searching for.

**Comment by benabus** [comment]
I think the idea here is that the "Article List" would replace the Graph title for Hoaxy so that it would show the currently selected articles, but no more.  Clicking a "more" button (or similar) would show the full list, allowing users to expand the graph.  We want to more closely associate the graphs with the articles that are selected to visualize.

**Comment by benabus** [comment]
Searching on Hoaxy automatically selects the first article to visualize.  The full list is hidden behind a button on the right side of the secondary search form (only visible when visualizing). Clicking on this button expands the list and allows users to select any number of articles to visualize.
