### ISSUE TITLE
Switch time chart tooltip to daily rate

### ISSUE THREAD

**Issue by glciampaglia** [IUNetSci/hoaxy-botometer#233]
When user hovers on time chart, tooltip should show daily tweets, not cumulated

**Comment by mihaivavram** [comment]
- Instead of "switch" we should add it as an extra label in the legend. Though I will say, this may take some time and may not be so trivial.

**Comment by filmenczer** [comment]
We discussed and decided to keep it simple by just changing the label on the tooltip to read "new tweets on DATE" and indicate the number for that bin rather than the cumulative.

**Comment by mihaivavram** [comment]
After further investigation it seems that the tooltip is very tightly coupled with the D3js plot, which means that in order to do what Fil suggested we must override this functionality and create our own tooltip.  This is not easy because the tooltip is very tightly coupled with many D3js components and there's also not a lot of documentation on how to do it (it seems like a black art and looking through D3js code and methods):

Simple
- Add an extra line in the plot for each respective claim/fact-check/tweet, so the Hoaxy search will yield 4 lines, and Twitter search 2
- This extra line will resemble the new tweets at that time interval and perhaps could have a legend key of "New Tweets" with a color of a lighter shade than the color of the line it is representing

Hacky and somewhat difficult:
- Grab a hold of the mouseover/mouseout event of the tooltip and dynamically change the text of the tooltip as Fil suggested

Difficult but robust:
- Create our own tooltip to do what Fil suggested

**Comment by mihaivavram** [comment]
This was completed with the following format:
```
<DATE>
<COLOR LEGEND BOX> New Tweets/Claims/Fact-Checks: <NUMBER OF NEW ENTITIES>
```
