### ISSUE TITLE
Run log upload to database script in test database and validate if insertions were done correctly, fixing discrepancies if needed

### ISSUE THREAD

**Issue by mihaivavram** [IUNetSci/hoaxy-botometer#39]

**Comment by mihaivavram** [comment]
Discrepancies:

- dtufreak anomaly where ip is 127.0.0.1 and timestamp is very large: 1427774914775
- how to store ip as the data does not seem to be consistent, should we make it consistent given a specific format?

**Comment by clayadavis** [comment]
> Some requests in the log seem to come from 127.0.0.1 is this alarming and/or should we treat these in a special way?

A while back I changed how IPs were logged in order to work with the Mashape API. This resulted in some erroneous IP addresses being logged. As long as there aren't any recent logs with 127.0.0.1, this is no reason to worry.

> Some timestamps (especially on beginning logs) are very large: 1427774914775, i.e. the year 47214!! Also what causes this discrepancy, it is worth looking into as it may be a bug.

Divide these by 1000. This is a discrepancy in how Javascript and Python report timestamps.

> How to store ip as the data does not seem to be consistent, i.e. some appear as ['<ip'>] and some appear as [<ip>] should we make it consistent given a specific format? Also should we keep the list format text or strip it as to have <ip>?

Strip quotes from any IPs in the logs. For now, when multiple IPs show up, just store IP addresses as a comma-separated list like so:

    164.132.43.69,164.132.43.69,54.88.51.199

Multiple IPs happen, for example, when the user is proxying their requests through another server. In the above example, a user from Paris is using a proxy hosted on Amazon EC2. Like most things in these logs, this has changed at some point in the past. Currently, I think the first IP in the list is the "real" IP of the user, so one could use the Postgres `split_part` function if they only wanted the first IP.

**Comment by clayadavis** [comment]
You'll probably find Python's string `strip` and `join` methods helpful for the above task involving IP addresses.

**Comment by mihaivavram** [comment]
Fixed the above mentioned points, next step is to run all/most of these logs in a test environment and check if there are anymore discrepancies in the results.

**Comment by mihaivavram** [comment]
The script is becoming relatively slow due to both the number of schema checks it does for each record, book-keeping of each type of record as well as the lookup query it performs for each record to append the number of requests done on that user. I am assuming this query will also be slower and slower the more records we have, hence now we are approaching around 4-8 hours per 1 gigabyte of data, so this would mean the total insertion process could take between a few days to a week depending on the power of the server that is running this script.

**Comment by clayadavis** [comment]
Speed isn't much of an issue since this only needs to be run once.

> the lookup query it performs for each record to append the number of requests done on that user

I don't think this needs to be done. If you're talking about the num_requests, it should be 0 for all inserted records. AFAIK there's no need to query the db before insert.

**Comment by clayadavis** [comment]
Furthermore, the types of schema checks you're doing are among the fastest operations in Python. The speed issues you're seeing are almost surely the result of interacting with the db. I think nixing the reads before insert will help a lot, and if you really need additional speed there are ways to do bulk inserts instead of a separate db operation for each record.

**Comment by mihaivavram** [comment]
> I don't think this needs to be done. If you're talking about the num_requests, it should be 0 for all inserted records. AFAIK there's no need to query the db before insert.

I'd be happy to remove this but doesn't it make sense that num_requests should be incremented by one each time we see a request for a given user? This is how num_requests will work in the future anyway so why not start early from the logs. Unless we are talking about two different fields here.

**Comment by clayadavis** [comment]
You're misunderstanding what `num_requests` does. We increment it by one every time we show a cached result to an API user. It should always be zero on insert-time, even when we're live.
